apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular17crud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular17crud
  template:
    metadata:
      labels:
        app: angular17crud
    spec:
      containers:
      - name: angular17crud
        image: viresh1994/angular-17-crud-example:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
