# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NodeJS CI

on:
  workflow_dispatch:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:

    runs-on: Angular

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build --if-present

      # - name: Run tests
      #   run: npm test -- --browsers=ChromeHeadless --no-watch --no-progress --bail

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/angular-17-crud-example:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/angular-17-crud-example:latest

      - name: Verify Docker image
        run: docker images
        
  deploy:
    name: Deploy to Minikube
    runs-on: Angular
    needs: build
    environment:
      name: production   # ðŸ‘ˆ requires manual approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Verify Helm
        run: helm version

      - name: Deploy using Helm
        run: |
          helm upgrade --install angular17crud-release ./angular17crud \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/angular-17-crud-example \
            --set image.tag=latest \
            --set image.pullPolicy=Always \
            --set service.type=NodePort \
            --set service.port=8080 \
            --set service.nodePort=30081

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/angular17crud-deployment --timeout=60s
          kubectl get pods -o wide
          kubectl get svc angular17crud-service
      
         
          
