name: Apply SCIM Schema

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  apply-schema:
    runs-on: Angular

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: github
          POSTGRES_PASSWORD: password
          POSTGRES_DB: scimdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U github"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install PostgreSQL client
      - name: Install PostgreSQL client
        run: |
            echo "viresh1994" | sudo -S apt-get update
            echo "viresh1994" | sudo -S apt-get install -y postgresql-client

      # Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432 -U github; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 3
          done

      - name: Show client version
        run: psql --version

      - name: List repo files
        run: |
          echo "Listing repository files..."
          ls -R
          
      - name: Debug â€“ validate SQL syntax
        env:
          PGPASSWORD: password
        run: |
          echo "Running in strict mode to catch errors"
          echo "\set ON_ERROR_STOP on" | cat - scripts/scim_schema.sql > scripts/sql_debug.sql
          psql -h localhost -U github -d postgres -f scripts/sql_debug.sql
   

      # Apply SCIM schema file
      - name: Apply SCIM schema
        env:
          PGPASSWORD: password
        run: |
          psql -h localhost -U github -d postgres -f scripts/scim_schema.sql

      - name: Verify SCIM tables created
        env:
          PGPASSWORD: password
        run: |
          echo "=== Listing SCIM tables ==="
          psql -h localhost -U github -d scimdb -c "\dt"

          echo -e "\n=== Describe SCIM Users Table ==="
          psql -h localhost -U github -d scimdb -c "\d scim_users"

          echo -e "\n=== Describe SCIM Groups Table ==="
          psql -h localhost -U github -d scimdb -c "\d scim_groups"

